### ISSUE TITLE
Anno-Auswertung: Filter nach Erhebung lädt keine Daten

### ISSUE THREAD

**Issue by MarkusPluschkovits** [german-in-austria/dioeDB#50]
Bei der Auswahl eines Erhebungssettings laden keine Daten mehr
![image](https://user-images.githubusercontent.com/60658004/142191114-07c84df7-582e-49b4-b513-c3bf0155926f.png)

**Comment by hcb79** [comment]
Das Problem scheint bei den importierten Antworten zu liegen ... die sind keinen Aufgaben zugeordnet ... das ist so nicht vorgesehen!
