### ISSUE TITLE
Feature: Import + Tagging von PP02/STX-Daten

### ISSUE THREAD

**Issue by MarkusPluschkovits** [german-in-austria/dioeDB#83]
Bisheriger Status war, dass die Timestamps aus der STX-Datei von PP02 genutzt werden konnten, um automatisch pro Gewährsperson in der KorpusDB Antworten zur entsprechenden Aufgabe zu erstellen (Ich bilde mir ein, dass zu diesem Zweck auch "is_audio_only" zum tbl_antworten hinzugefügt wurde, da ihre Antworten nicht transkribiert sind). Dazu wurden Audiofile (als .ogg) und dazugehörige STX-File in das "allfb02"-Verzeichnis der DB hinterlegt. Anschließend konnte via KorpusDB --> InfErhebung bei der jeweiligen Erhebung die Audiofile zugeordnet werden, und anschließend die STX-File über einen Knopfdruck pro InfErhebung importiert werden konnte (der match von Audio zu STX war glaube ich via dem Namen, ich weiß aber nicht mehr ob das manuell herausgesucht werden musste)... (Ich glaube der Importer ist hier: https://github.com/german-in-austria/dioeDB/blob/master/app/KorpusDB/views.py#L714-L716:~:text=if%20%27stxsmfxfunction%27,vorhanden!%3C/b%3E%3Cbr%3E%27).

Im Prinzip wollen wir wieder genau das gleiche, nur sollen dieses Mal aus dem TR:6 in der STX-File automatisch Tags zu diesen Antworten generiert werden (wenn vorhanden, nicht alle aufgaben werden getagged). Ich hab dir Beispielfiles dazu hier in der Cloud hinterlegt: https://dioecloud.trans.univie.ac.at/index.php/f/6257614 (die zugehörigen .oggs der .wavs liegen bereits im allfb02-Verzeichnis). 
2 Problematiken sehe ich: die erste wäre, dass für ca. die Hälfte der Daten schon Antworten existieren (Beispieldatei ist eine davon) - wir haben das ja bereits alles importiert, aber da gingen alle Beteiligten noch davon aus, dass das Taggen in der DB stattfinden wird... Wir müssten also entweder alle Antworten zu PP02-Erhebungen im Bulk löschen (habe vorgewarnt, dass das passieren kann), oder nur noch die Tags (+ evtl. leicht andere Timestamps importieren). Zweitere Problematik wäre, dass die eine weitere Erhebungsrunde haben, die genauso importiert werden soll, aber mit anderen Aufgaben - also eventuell muss man den Importer dann noch einmal anpassen... 

Ich bin mir auch noch nicht sicher wie unproblematisch ihre Tagbezeichnungen sind, da würde ich aber eventuell eine Übersetzungsliste bereitstellen, wie die entsprechenden Tags dann in der DB heißen, und welche ID sie haben. Ebenfalls fraglich ist es, wie sich der bisherige Importer tut, wenn es zwei Segmente gibt, die einer Aufgabe zugewiesen sind (werden das dann zwei Antworten zu einer Aufgabe? Das wäre die Ideallösung!). Bei Rückfragen oder so sag Bescheid!

**Comment by hcb79** [comment]
@MarkusPluschkovits Erledigt?

**Comment by MarkusPluschkovits** [comment]
> @MarkusPluschkovits Erledigt?

ist alles erledigt, vielen Dank Hansi! :)
